---
# Cyber Security Class
# Walcott Denison III

# Set up for playbook
- name: install filebeat and launch
  hosts: webservers
  become: yes
  tasks:

# get the file needed
  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

# Install it
  - name: Install Filebeat
    command: dpkg -i filebeat-7.6.1-amd64.deb

# copy the config file to the remote server
  - name: copy in filebeat-config.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

# get it going on the remote sever
  - name: enable and configure system module
    command: filebeat modules enable system

# Set it up
  - name: setup filebeat
    command: filebeat setup

# start the filebeat service
  - name: start filebeat service
    command: service filebeat start

# set up auto start on boot
  - name: enable serviice filebeat on boot
    systemd:
      name: filebeat
      enabled: yes

